# Generated by Django 5.1.5 on 2025-01-25 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_contactmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
    ]
