# Generated by Django 5.1.5 on 2025-01-25 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='email',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
