# Generated by Django 5.1.5 on 2025-01-25 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_contactmessage_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuorses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('price', models.IntegerField()),
                ('day', models.TextField()),
                ('oportunities', models.TextField()),
            ],
        ),
    ]
